schema_version = "1.0.0"

id = "lks_quadgrab"
version = "1.1.3"
name = "LKS QuadGrab"
tagline = "QuadGrab"
maintainer = "LKS <Liam@lksgraphics.ca>"
type = "add-on"
website = "https://github.com/LiamSmyth/LKS_QuadGrab"
license = ["SPDX:GPL-2.0-or-later"]
blender_version_min = "4.2.0"

[permissions]
network = "Need network access to download dependencies"
files = "Need file access to save textures"
clipboard = "Need clipboard access to copy paths"

[build]
paths_exclude_pattern = [
    "__pycache__/",
    ".*",
    "/*.zip",
    "*.blend*",
    "/tests/",
    "/debug/",
    "/docs/",
    "/examples/",
    "/prompt/",
    "/quadgrab/",
    "/dependencies/",
    "*.bat",
    "*.md",
    "/test.py",
    "/main.py",
    "/publish_*.py",
    "/release.py",
    "/requirements.txt",
]
