schema_version = "1.0.0"

id = "lks_quadgrab"
version = "1.1.2"
name = "LKS QuadGrab"
tagline = "QuadGrab"
maintainer = "LKS <Liam@lksgraphics.ca>"
type = "add-on"
website = "https://github.com/LiamSmyth/LKS_QuadGrab"
license = ["SPDX:GPL-2.0-or-later"]
blender_version_min = "4.2.0"

[permissions]
network = "Need network access to download dependencies"
files = "Need file access to save textures"
clipboard = "Need clipboard access to copy paths"

[build]
paths = [
    "__init__.py",
    "overlay.py",
    "properties.py",
    "register_quadgrab.py",
    "ui.py",
    "ops/",
    "util/",
]
